swagger: '2.0'
info:
  x-ibm-name: logistics
  title: logistics
  version: 1.0.7
schemes:
  - https
basePath: /logistics
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  clientID:
    description: ''
    in: header
    name: X-IBM-Client-Id
    type: apiKey
security:
  - {}
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  gateway: datapower-gateway
  catalogs:
    apic-dev:
      properties:
        runtime-url: $(TARGET_URL)
  properties:
    shipping_svc_url:
      value: 'http://shipping.think.ibm:5000/calculate'
      description: Location of the shipping calculator service
      encoded: false
  assembly:
    execute:
      - activity-log:
          title: activity-log
          content: payload
          error-content: payload
          version: 1.0.0
      - invoke:
          title: invoke_geolocate
          timeout: 60
          verb: GET
          cache-response: protocol
          cache-ttl: 900
          version: 1.0.0
          target-url: >-
            http://nominatim.openstreetmap.org/search?postalcode={zip}&format=json
          output: geocode_response
      - gatewayscript:
          title: format-maps-link
          version: 1.0.0
          source: "// Require API Connect functions\r\nvar apic = require('local:///isp/policy/apim.custom.js');\r\n// Save the geocode service response body to a variable\r\nvar mapsApiResponse = apic.getvariable('geocode_response.body');\r\n// Get location attributes from the response message\r\nvar location = mapsApiResponse[0];\r\nvar storesResponse = {\r\n\"maps_link\": 'https://www.openstreetmap.org/#map=16/' +\r\nlocation.lat + '/' + location.lon\r\n};\r\n// Save the output\r\napic.setvariable('message.body', storesResponse);"
    catch: []
paths:
  /stores:
    get:
      responses:
        '200':
          description: 200 OK
          schema:
            $ref: '#/definitions/store_location'
      tags:
        - stores
      summary: Locate store near zip code
      operationId: get.stores
      parameters:
        - name: zip
          type: string
          required: true
          in: query
          description: zip code
      description: Locate store near zip code
definitions:
  rates:
    properties:
      next_day:
        type: string
        example: '20.00'
      two_day:
        type: string
        example: '17.00'
      ground:
        type: string
        example: '8.00'
    required:
      - two_day
      - next_day
      - ground
  shipping:
    properties:
      xyz:
        type: string
        $ref: '#/definitions/rates'
      cek:
        type: string
        $ref: '#/definitions/rates'
    required:
      - xyz
      - cek
  store_location:
    properties:
      google_maps_link:
        type: string
        example: 'https://www.google.com/maps?q=34.1030032,-118.4104684'
    required:
      - google_maps_link
